USE [master]
GO

/****** Object:  Database [QUANLYBONGDA]    Script Date: 05/05/2022 4:30:20 PM ******/
CREATE DATABASE [QUANLYBONGDA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QUANLYBONGDA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QUANLYBONGDA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QUANLYBONGDA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QUANLYBONGDA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QUANLYBONGDA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QUANLYBONGDA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET ARITHABORT OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [QUANLYBONGDA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QUANLYBONGDA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QUANLYBONGDA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QUANLYBONGDA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QUANLYBONGDA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QUANLYBONGDA] SET  MULTI_USER 
GO

ALTER DATABASE [QUANLYBONGDA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QUANLYBONGDA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QUANLYBONGDA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QUANLYBONGDA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QUANLYBONGDA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QUANLYBONGDA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QUANLYBONGDA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QUANLYBONGDA] SET  READ_WRITE 
GO

